### ISSUE TITLE
Error: The header content contains invalid characters

### ISSUE THREAD

**Issue by LarsVoith** [Telerik-Verified-Plugins/Keychain-Sharing#2]
Hi I'm trying to add this plugin to my app, but I'm getting error 1 after I add the plugin with the CLI.  If i try to build the app i'm getting Error #2 in the log file.

Thanks

1.Error: The header content contains invalid characters (and it is not adding it to the config.xml)
2.Error: Variable(s) missing: KEYCHAIN_ACCESS_GROUP

**1. when try to add the plugin via CLI:**
my-MacBook-Pro:CLI_App3 me$ phonegap plugin add https://github.com/Telerik-Verified-Plugins/Keychain-Sharing.git --variable KEYCHAIN_ACCESS_GROUP=com.my.id —save
Fetching plugin "https://github.com/Telerik-Verified-Plugins/Keychain-Sharing.git" via git clone
Repository "https://github.com/Telerik-Verified-Plugins/Keychain-Sharing.git" checked out to git ref "master".

Installing "cordova-plugin-keychainsharing" for ios

KeychainSharing prerequisites

Running hook to add iOS Keychain Sharing entitlements

iosFolder: /Users/me/Documents/Adobe/PhoneGap/CLI_App3/platforms/ios/

Will add iOS Keychain Sharing entitlements to project 'App3'

KeychainSharingBundleID passed in as variable: com.my.id

OK, added iOS Keychain Sharing entitlements to project 'App3'

Error: The header content contains invalid characters

**2.If i try to build i get the following in my log file:**
Installing "cordova-plugin-keychainsharing" at "1.0.1" for ios
Failed to install 'cordova-plugin-keychainsharing':Error: Variable(s) missing: KEYCHAIN_ACCESS_GROUP
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:347:23
    at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:557:44
    at flush (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
Variable(s) missing: KEYCHAIN_ACCESS_GROUP

**Comment by EddyVerbruggen** [comment]
Just to be sure, did you also try passing in the variable with `"` quotes? Like: `cordova plugin add https://github.com/Telerik-Verified-Plugins/Keychain-Sharing.git --variable KEYCHAIN_ACCESS_GROUP="com.my.id"`

**Comment by LarsVoith** [comment]
with the quotes it just returns ">" and does nothing --- with out the quotes it will fetch the file.

**Comment by EddyVerbruggen** [comment]
Sounds like a typo in the Terminal (wrong type of quotes perhaps?)

**Comment by LarsVoith** [comment]
ok I was able to add the quotes
 phonegap plugin add https://github.com/Telerik-Verified-Plugins/Keychain-Sharing.git --variable KEYCHAIN_ACCESS_GROUP="com.my.id" —save

But still getting Error: The header content contains invalid characters
